package:
  name: prism-dev
  version: 1.0.0

requirements:
  run:
    - make
    - {{ compiler('cxx') }}
    - fmt
    - yaml-cpp
    - lcov
    - gtest
    - clang-format
    - clang-tools 


channels:
  - conda-forge
  - defaults

extra:
  recipe-maintainers:
    - gsgall

about:
  home: asdf
  license: test
  summary: "A simple conda package that creates activate and deactivate scripts and installs a few packages."
