name: Bug Report
description: Report a bug that is preventing proper use of this library
labels: 'T: defect, P: normal'

body:
- type: markdown
  attributes:
    value: >
      #### Before submitting a bug, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/gsgall/rxn-cpp/issues).
- type: textarea
  attributes:
    label: Bug Description
    description: |
      A clear and concise description of the problem (Note: A missing feature is not a bug).
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to Reproduce
    description: |
      In order to make it easier for us to address your issue we request that you write a test to be added to the test suite that covers your case.
      If you need help writing a case please first look at the examples in the `test/tests` directory and if you need further assistance please reach out on the discussions forum (https://github.com/gsgall/rxn-cpp/discussions).
  validations:
    required: true
- type: textarea
  attributes:
    label: Impact
    description: |
      Does this prevent you from getting your work done, or is it more of an annoyance?
  validations:
    required: true

- type: markdown
  attributes:
    value: >
      Thanks for contributing!
