blank_issues_enabled: true
contact_links:
  - name: Questions
    url: https://github.com/gsgall/rxn-cpp/discussions
    about: Ask general questions about rxn-cpp and discuss with other community members.
