blank_issues_enabled: true
contact_links:
  - name: Questions
    url: https://github.com/NCSU-ComPS-Group/prism/discussions
    about: Ask general questions about PRISM and discuss with other community members.
