Content:
    rxn-cpp:
        root_dir: ${ROOT_DIR}/content
    moose:
        root_dir: ${MOOSE_DIR}/framework/doc/content
        content:
            - js/*
            - css/*
            - contrib/**
            - media/**


Renderer:
    type: MooseDocs.base.MaterializeRenderer
    extra-css:
        - css/zapdos.css

Extensions:
    MooseDocs.extensions.navigation:
        name: rxn-cpp
        repo: https://github.ncsu.edu/NCSU-ComPS-Group/rxn-cpp
        menu:
            Doxygen: doxygen/html/annotated.html
            Getting Started:
                Installation: getting_started/installation.md
                Input Syntax: getting_started/input_syntax.md
                Updating: getting_started/staying_upto_date.md
            How it Works:
                Reaction Parsing: how_it_works/reaction_parsing.md
                Species Parsing: how_it_works/species_parsing.md


    MooseDocs.extensions.appsyntax: disable
