package:
  name: prism
  version: 1.0.0

requirements:
  build:
    - make
    - yaml-cpp
    - fmt

  run:
    - fmt
    - yaml-cpp
    - {{ moose_ld64 }}          # [osx]
    - {{ moose_libclang }}      # [osx]
    - {{ moose_libclang13 }}    # [osx]
    - {{ moose_clangcc }}       # [osx]
    - {{ moose_clangxx }}       # [osx]
    - {{ moose_gcc }}           # [linux]
    - gxx                       # [linux]
    - make

channels:
  - conda-forge
  - defaults

extra:
  recipe-maintainers:
    - gsgall

about:
  home: asdf
  license: test
  summary: "A simple conda package that creates activate and deactivate scripts and installs a few packages."
