name: linux-build

on:
  push:
    branches:
      - main

jobs:
  linux-build:
    runs-on: ubuntu-latest
    # Set up a default shell for all steps
    # See: https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Mambaforge3 and conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Mambaforge
        use-mamba: true
        activate-environment: rxn-cpp
        environment-file: scripts/conda_environment.yml
    # GitHub-hosted runners are currently limited to 4 cores
    # See: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    - name: Build and run tests
      run: |
        conda activate rxn-cpp
        export LD_LIBRARY_PATH="$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"
        make -j 4
        ./main
        cd test
        make -j 4
        ./run_tests -j 4
