name: macos-build

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - devel

jobs:
  macos-build:
    environment: manual-approval
    runs-on: macos-latest
    # Set up a default shell for all steps
    # See: https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - name: Checkout branch
      uses: actions/checkout@v6
      with:
        submodules: true
    - name: Set up Mambaforge3 and conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        activate-environment: initial
        channels: conda-forge
        conda-remove-defaults: true
    - name: Build Package
      run: |
        conda install -y conda-build
        mkdir -p build
        conda build conda/prism-dev --output-folder build
        conda create -y -n prism-dev
        conda activate prism-dev
        conda install -y prism-dev -c ./build 
    # GitHub-hosted runners are currently limited to 4 cores
    # See: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    - name: Build main, and library directly
      run: |
        conda activate prism-dev
        make -j 4
        ./main
        make clean
    - name: Build and run main with dll
      run: |
        conda activate prism-dev
        make -f Makefile-as-dll install -j 4
        make -f Makefile-with-dll -j 4
        ./main
    - name: Build and run tests directly
      run: |
        cd test
        conda activate prism-dev
        make -j 4
        ./run_tests -j 4
        make clean
    - name: Build and run tests with dll
      run: |
        cd test
        conda activate prism-dev
        make -f Makefile-with-dll -j 4
        ./run_tests -j 4
