name: macos-build-dll

on:
  push:
    branches:
      - devel

jobs:
  macos-build:
    runs-on: macos-latest
    # Set up a default shell for all steps
    # See: https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Mambaforge3 and conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Mambaforge
        use-mamba: true
        activate-environment: prism
        environment-file: scripts/conda_env.yml
    - name: Install Compiler
      run: |
        conda activate prism
        conda install -y clangxx
        export CXX=$(which clang++)
    # GitHub-hosted runners are currently limited to 4 cores
    # See: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    - name: Build and run tests
      run: |
        conda activate prism
        make -j 4
        ./main
        make clean
        make -f Makefile-as-dll install -j 4
        make -f Makefile-with-dll -j 4
        ./main
        cd test
        make -j 4
        ./run_tests -j 4
        make clean
        make -f Makefile-with-dll -j 4
        ./run_tests -j 4
